version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile     # тот же файл
      target: python-base        # → запустим runserver
    env_file: .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./materials:/app/materials
      - ./db.sqlite3:/app/db.sqlite3
    ports: ["8000:8000"]

  frontend:
    image: node:20-alpine
    working_dir: /frontend
    command: sh -c "npm ci && npm run dev -- --host"
    volumes:
      - ./frontend:/frontend
    env_file: .env.dev
    ports: ["5173:5173"]