# Generated by Django 5.2.3 on 2025-06-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='responsible',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ответственный (ФИО)'),
        ),
        migrations.AddField(
            model_name='work',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, default=2025),
        ),
    ]
