# Generated by Django 5.2.3 on 2025-06-23 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_work_responsible_work_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(upload_to='materials/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='QuarterReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')])),
                ('accrual_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_sum', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_acc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='budget.budgetitem')),
            ],
            options={
                'unique_together': {('item', 'year', 'quarter')},
            },
        ),
    ]
