# Generated by Django 5.2.3 on 2025-06-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_material_file_quarterreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='vat_rate',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (20, '20%')], default=0, help_text='Процент НДС', verbose_name='Ставка НДС'),
        ),
    ]
