# Generated by Django 5.2.3 on 2025-06-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_work_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='group',
            field=models.CharField(choices=[('cert', 'Расходы на сертификацию, патентование и метрологию, качество'), ('general', 'Общехозяйственные расходы')], default='cert', help_text='Категория статьи бюджета', max_length=50, verbose_name='Группа'),
        ),
    ]
