# Generated by Django 5.2.3 on 2025-06-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_budgetitem_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше значение — выше в списке', verbose_name='Позиция'),
        ),
    ]
