# Generated by Django 5.2.3 on 2025-06-24 15:15

import django.db.models.deletion
from django.db import migrations, models


def populate_groups(apps, schema_editor):
    Group = apps.get_model('budget', 'Group')
    BudgetItem = apps.get_model('budget', 'BudgetItem')

    # create group entries matching old string values
    g_cert, _ = Group.objects.get_or_create(code='cert', defaults={'name': 'Расходы на сертификацию, патентование и метрологию, качество'})
    g_gen, _ = Group.objects.get_or_create(code='general', defaults={'name': 'Общехозяйственные расходы'})
    g_inv, _ = Group.objects.get_or_create(code='invest', defaults={'name': 'Инвестиции'})

    # re-link existing BudgetItems from old char to new FK
    for bi in BudgetItem.objects.all():
        old = bi.group  # still CharField at this point
        if old == 'cert':
            bi.group = str(g_cert.pk)
        elif old == 'general':
            bi.group = str(g_gen.pk)
        elif old == 'invest':
            bi.group = str(g_inv.pk)
        bi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budgetitem_options_budgetitem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код группы')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование группы')),
            ],
            options={
                'verbose_name': 'Группа статьи',
                'verbose_name_plural': 'Группы статей',
            },
        ),
        migrations.RunPython(populate_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='budgetitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='budget.group', verbose_name='Группа'),
        ),
    ]
