# Generated by Django 5.2.3 on 2025-06-24 15:31
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0008_auto_20250624_1524'),
        ('budget', '0009_auto_20250624_1526'),
    ]

    operations = []