# Generated by Django 5.2.3 on 2025-06-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_merge_0008_auto_20250624_1524_0009_auto_20250624_1526'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': [('change_any_work', 'Can edit any work regardless of responsible user')]},
        ),
        migrations.AlterField(
            model_name='work',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
