# Generated by Django 5.2.3 on 2025-06-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_alter_work_options_alter_work_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='feasibility',
            field=models.CharField(choices=[('green', 'Выполнима'), ('yellow', 'Вероятно выполнима'), ('red', 'Скорее не выполнима')], default='green', max_length=10, verbose_name='Возможность реализации'),
        ),
    ]
