# Generated by Django 5.2.3 on 2025-07-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_work_feasibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='№ сертификата (для ИК)'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='certification',
            field=models.BooleanField(default=False, help_text='Отмечается, если требуется сертификация', verbose_name='Сертификация'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='certification_body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Орган по сертификации'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование продукта'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='responsible_dpm',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответственный от ДПМ'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='responsible_slok',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответственный от СлОК'),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='work_type',
            field=models.CharField(blank=True, choices=[('ИК_СС_ТР_ТС', 'ИК СС ТР ТС'), ('ИК_СС_ГОСТ', 'ИК СС ГОСТ'), ('СС_ТР_ТС', 'СС ТР ТС'), ('ДС_ТР_ТС', 'ДС ТР ТС'), ('СС_ПБ', 'СС ПБ'), ('СС_ГОСТ', 'СС ГОСТ'), ('НОТИФИКАЦИЯ', 'Нотификация'), ('СГР', 'СГР'), ('МИНПРОМТОРГ', 'МИНПРОМТОРГ'), ('УТСИ', 'УТСИ')], max_length=20, null=True, verbose_name='Вид работы'),
        ),
    ]
