# Generated by Django 5.2.3 on 2025-07-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_budgetitem_certificate_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма факта')),
                ('creditor', models.CharField(blank=True, max_length=255, verbose_name='Кредитор')),
                ('contract', models.CharField(blank=True, max_length=255, verbose_name='Договор')),
                ('pfm', models.CharField(default='11000900', max_length=20, verbose_name='ПФМ')),
                ('fp', models.CharField(max_length=50, verbose_name='ФП')),
                ('mvz', models.CharField(blank=True, max_length=255, verbose_name='МВЗ')),
                ('mm', models.CharField(blank=True, max_length=255, verbose_name='ММ')),
                ('payment_document', models.CharField(blank=True, max_length=255, verbose_name='Документ на оплату')),
                ('payment_close', models.CharField(blank=True, max_length=255, verbose_name='Закрытие оплаты')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('comment_file', models.FileField(blank=True, null=True, upload_to='payment_comments/', verbose_name='Файл комментария')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='budget.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Деталь оплаты',
                'verbose_name_plural': 'Детали оплат',
                'unique_together': {('work', 'month')},
            },
        ),
    ]
