# Generated by Django 5.2.3 on 2025-07-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_work_certificate_number_work_certification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccrualDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=3, verbose_name='Месяц')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма факта')),
                ('closing_document', models.CharField(blank=True, max_length=255, verbose_name='Документ закрытия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('comment_file', models.FileField(blank=True, null=True, upload_to='accrual_comments/', verbose_name='Файл комментария')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_details', to='budget.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Деталь начисления',
                'verbose_name_plural': 'Детали начислений',
                'unique_together': {('work', 'month')},
            },
        ),
    ]
