# Generated by Django 5.2.3 on 2025-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_accrualdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualdetail',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='accrualdetail',
            name='transfer_reason',
            field=models.TextField(blank=True, verbose_name='Причина переноса'),
        ),
    ]
