# Generated by Django 5.2.3 on 2025-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_accrualdetail_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='cancel_reason',
            field=models.TextField(blank=True, verbose_name='Причина отмены оплаты'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='transfer_reason',
            field=models.TextField(blank=True, verbose_name='Причина переноса оплаты'),
        ),
    ]
