# Generated by Django 5.2.3 on 2025-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_paymentdetail_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accrualdetail',
            name='month',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='month',
            field=models.CharField(db_index=True, max_length=3, verbose_name='Месяц'),
        ),
        migrations.AddIndex(
            model_name='accrualdetail',
            index=models.Index(fields=['work', 'month'], name='budget_accr_work_id_776de3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdetail',
            index=models.Index(fields=['work', 'month'], name='budget_paym_work_id_97b018_idx'),
        ),
    ]
