# Generated by Django 5.2.3 on 2025-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_alter_accrualdetail_month_alter_paymentdetail_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accrualdetail',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='Причина корректировки'),
        ),
        migrations.AddField(
            model_name='accrualdetail',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='Корректировка'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='Причина корректировки оплаты'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='is_correction',
            field=models.BooleanField(default=False, verbose_name='Корректировка'),
        ),
    ]
