# Generated by Django 5.2.3 on 2025-07-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_accrualdetail_correction_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
