# Generated by Django 5.2.3 on 2025-07-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_alter_work_comment_alter_work_justification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='item_reports/%Y/%m', verbose_name='Файл отчета')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='budget.budgetitem', verbose_name='Статья бюджета')),
            ],
            options={
                'verbose_name': 'Отчет по статье',
                'verbose_name_plural': 'Отчеты по статьям бюджета',
            },
        ),
    ]
