# Generated by Django 5.2.3 on 2025-07-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_articlereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='budget.budgetitem', verbose_name='Статья бюджета'),
        ),
        migrations.AlterField(
            model_name='material',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='budget.work'),
        ),
    ]
